# Generated by Django 6.0.4 on 2026-05-10 09:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSystemSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('capture_date', models.DateField(db_index=True, unique=True)),
                ('total_video_count', models.IntegerField(default=0)),
                ('total_storage_gb', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_duration_minutes', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-capture_date'],
            },
        ),
        migrations.CreateModel(
            name='VideoCalculatedUnitCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('cost_per_gb_cents', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cost_per_video_cents', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cost_per_minute_cents', models.DecimalField(decimal_places=4, max_digits=12)),
                ('total_monthly_infrastructure_burn_cents', models.BigIntegerField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_cost_engine.videosystemsnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
