# Generated by Django 6.0.4 on 2026-05-11 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('equipment_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_working_day', models.BooleanField(default=True)),
                ('daily_capacity_hours', models.DecimalField(decimal_places=2, default=24.0, max_digits=6)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Production Manager'), ('cameraman', 'Cameraman'), ('editor', 'Editor'), ('designer', 'Designer'), ('reviewer', 'Reviewer'), ('uploader', 'Uploader')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProductionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('branch', models.CharField(choices=[('science', 'Science'), ('literal', 'Literal'), ('ninth', 'Ninth Grade'), ('other', 'Other')], max_length=50)),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField(blank=True, null=True)),
                ('shooting_date', models.DateField(blank=True, null=True)),
                ('shooting_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('shooting', 'Shooting'), ('editing', 'Editing'), ('reviewing', 'Reviewing'), ('designing', 'Designing'), ('ready', 'Ready to Upload'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('canceled', 'Canceled')], default='scheduled', max_length=20)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production_management.productionroom')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('shooting', 'Shooting'), ('editing', 'Editing'), ('reviewing', 'Reviewing'), ('designing', 'Designing'), ('ready', 'Ready to Upload'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('canceled', 'Canceled')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='production_management.teacherproductionsession')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('shooting', 'Shooting'), ('editing', 'Editing'), ('designing', 'Designing'), ('reviewing', 'Reviewing'), ('uploading', 'Uploading')], max_length=20)),
                ('estimated_duration_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actual_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production_management.productionmember')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='production_management.teacherproductionsession')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('teacher_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('production_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='production_management.teacherproductionsession')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('message', models.CharField(max_length=255)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='production_management.teacherproductionsession')),
            ],
        ),
    ]
