# Generated by Django 6.0.4 on 2026-05-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherproductionsession',
            name='branch',
            field=models.CharField(choices=[('science', 'علمي'), ('literal', 'أدبي'), ('ninth', 'تاسع'), ('other', 'أخرى')], max_length=50),
        ),
    ]
