# Generated by Django 6.0.4 on 2026-05-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0003_alter_productiontimeline_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255, verbose_name='اسم المادة')),
                ('branch', models.CharField(choices=[('science', 'علمي'), ('literal', 'أدبي'), ('ninth', 'تاسع')], max_length=50, verbose_name='الفرع')),
                ('exam_date', models.DateField(verbose_name='تاريخ الامتحان')),
                ('exam_time', models.TimeField(blank=True, null=True, verbose_name='وقت الامتحان')),
                ('duration', models.CharField(default='2', max_length=10, verbose_name='المدة (ساعات)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'موعد امتحان',
                'verbose_name_plural': 'جدول الامتحانات',
                'ordering': ['exam_date'],
                'unique_together': {('subject_name', 'branch')},
            },
        ),
    ]
