# Generated by Django 6.0.4 on 2026-05-11 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_course_allow_pdf_download_course_pdf_file'),
        ('production_management', '0004_examscheduleentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherproductionsession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_sessions', to='learning.course', verbose_name='الدورة على المنصة'),
        ),
    ]
