# Generated by Django 6.0.4 on 2026-05-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0005_teacherproductionsession_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiontimeline',
            name='status',
            field=models.CharField(choices=[('scheduled', 'مجدول'), ('confirmed', 'مصادق عليه'), ('shooting', 'تصوير'), ('editing', 'مونتاج'), ('reviewing', 'مراجعة'), ('designing', 'تصميم'), ('ready', 'جاهز للرفع'), ('completed', 'مكتمل'), ('delayed', 'متأخر'), ('canceled', 'ملغي')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherproductionsession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'مجدول'), ('confirmed', 'مصادق عليه'), ('shooting', 'تصوير'), ('editing', 'مونتاج'), ('reviewing', 'مراجعة'), ('designing', 'تصميم'), ('ready', 'جاهز للرفع'), ('completed', 'مكتمل'), ('delayed', 'متأخر'), ('canceled', 'ملغي')], default='scheduled', max_length=20),
        ),
    ]
