# Generated by Django 6.0.4 on 2026-05-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0006_alter_productiontimeline_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherproductionsession',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
