# Generated by Django 6.0.4 on 2026-05-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0007_alter_teacherproductionsession_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherproductionsession',
            name='shooting_duration_days',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد أيام التصوير'),
        ),
    ]
