# Generated by Django 6.0.4 on 2026-05-10 09:50

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BunnyPlatformReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('period', models.DateField(unique=True)),
                ('total_aggregate_cost_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_storage_used_gb', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_bandwidth_used_gb', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='BunnyRateConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('monthly_vps_cost_cents', models.BigIntegerField(default=5000, help_text='External server costs')),
                ('price_per_gb_storage', models.DecimalField(decimal_places=5, default=0.01, max_digits=10)),
                ('price_per_gb_bandwidth', models.DecimalField(decimal_places=5, default=0.005, max_digits=10)),
                ('encoding_per_min', models.DecimalField(decimal_places=5, default=0.001, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BunnyVideoAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('bunny_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('storage_size_bytes', models.BigIntegerField(default=0)),
                ('bandwidth_used_bytes', models.BigIntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('total_views', models.BigIntegerField(default=0)),
                ('calculated_total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-calculated_total_cost_usd'],
            },
        ),
    ]
