# Generated by Django 6.0.4 on 2026-05-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_accesscodebatch_code_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institutes/logos/'),
        ),
    ]
