# Generated by Django 6.0.4 on 2026-05-05 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_institute_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesscode',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_access_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesscode',
            name='sold_price_cents',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
