# Generated by Django 6.0.4 on 2026-05-05 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_accesscode_sold_at_accesscode_sold_by_and_more'),
        ('learning', '0007_alter_certificate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='access_type',
            field=models.CharField(choices=[('course', 'Course'), ('lesson', 'Lesson'), ('subscription', 'Subscription'), ('package', 'Package')], default='course', max_length=20),
        ),
        migrations.CreateModel(
            name='CoursePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.SlugField(unique=True)),
                ('price_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(related_name='billing_packages', to='learning.course')),
            ],
            options={
                'verbose_name': 'باقة دورات',
                'verbose_name_plural': 'باقات الدورات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='accesscode',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_codes', to='billing.coursepackage'),
        ),
    ]
