# Generated by Django 6.0.4 on 2026-05-05 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_accesscode_access_type_coursepackage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCodePrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards_count', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_logs', to='billing.accesscodebatch')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_code_prints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل طباعة أكواد',
                'verbose_name_plural': 'سجلات طباعة الأكواد',
                'ordering': ['-created_at'],
            },
        ),
    ]
