# Generated by Django 6.0.4 on 2026-05-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_accesscodeprintlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepackage',
            name='auto_include_shared',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coursepackage',
            name='package_track',
            field=models.CharField(choices=[('custom', 'Custom'), ('scientific', 'Scientific'), ('literary', 'Literary'), ('ninth', 'Ninth')], default='custom', max_length=24),
        ),
    ]
