# Generated by Django 6.0.4 on 2026-05-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_coursepackage_auto_include_shared_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepackage',
            name='package_track',
            field=models.CharField(choices=[('custom', 'مخصصة'), ('scientific', 'علمي'), ('literary', 'أدبي'), ('ninth', 'تاسع')], default='custom', max_length=24),
        ),
    ]
