# Generated by Django 6.0.4 on 2026-05-06 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_coursepackage_package_track'),
        ('learning', '0009_alter_course_academic_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscodebatch',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_batches', to='billing.coursepackage'),
        ),
        migrations.AlterField(
            model_name='accesscodebatch',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_batches', to='learning.course'),
        ),
    ]
