# Generated by Django 6.0.4 on 2026-05-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_accesscodebatch_package_alter_accesscodebatch_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='اسم الحسم')),
                ('starts_at', models.DateTimeField(verbose_name='تاريخ البدء')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='نسبة الحسم (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'قاعدة حسم',
                'verbose_name_plural': 'قواعد الحسومات',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.AddField(
            model_name='accesscode',
            name='price_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
