# Generated by Django 6.0.4 on 2026-05-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_discountrule_accesscode_price_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountrule',
            options={'ordering': ['-id'], 'verbose_name': 'قاعدة حسم', 'verbose_name_plural': 'قواعد الحسومات'},
        ),
        migrations.AddField(
            model_name='discountrule',
            name='academic_track',
            field=models.CharField(choices=[('all', 'كافة الفروع'), ('scientific', 'علمي'), ('literary', 'أدبي'), ('ninth', 'تاسع'), ('general', 'مشترك')], default='all', max_length=24, verbose_name='الفرع المستهدف'),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='discount_amount_syp',
            field=models.PositiveIntegerField(default=0, verbose_name='قيمة الحسم بالليرة (ل.س)'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء'),
        ),
    ]
