# Generated by Django 6.0.4 on 2026-06-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_alter_discountrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessgrant',
            name='file1_printed',
            field=models.PositiveIntegerField(default=0, verbose_name='مرات طباعة الملف الإضافي 1'),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='file2_printed',
            field=models.PositiveIntegerField(default=0, verbose_name='مرات طباعة الملف الإضافي 2'),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='main_pdf_printed',
            field=models.PositiveIntegerField(default=0, verbose_name='مرات طباعة ملف المادة'),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='print_password',
            field=models.CharField(blank=True, max_length=40, verbose_name='كلمة مرور الطباعة'),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='print_quota',
            field=models.PositiveIntegerField(default=2, verbose_name='الحد الأقصى للطباعة'),
        ),
    ]
