# Generated by Django 6.0.4 on 2026-06-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_accessgrant_file1_printed_accessgrant_file2_printed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessgrant',
            name='view_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد مرات فتح PDF'),
        ),
    ]
