# Generated by Django 6.0.4 on 2026-06-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_accessgrant_view_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='اسم الإعداد')),
                ('key', models.CharField(max_length=80, unique=True, verbose_name='مفتاح الإعداد')),
                ('value_numeric', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='القيمة العددية')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='العنوان بالعربي')),
            ],
            options={
                'verbose_name': 'إعداد مالي',
                'verbose_name_plural': 'الإعدادات المالية',
            },
        ),
        migrations.AddField(
            model_name='salescenter',
            name='collected_amount_syp',
            field=models.PositiveIntegerField(default=0, verbose_name='المبالغ المحصلة (ل.س)'),
        ),
        migrations.AddField(
            model_name='salescenter',
            name='is_settled',
            field=models.BooleanField(default=False, verbose_name='تمت التسوية'),
        ),
    ]
