# Generated by Django 6.0.4 on 2026-06-18 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_billingsetting_salescenter_collected_amount_syp_and_more'),
        ('learning', '0014_course_custom_expense_syp_course_hosting_months_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المصروف')),
                ('amount_syp', models.PositiveIntegerField(default=0, verbose_name='المبلغ بالليرة السورية')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المبلغ بالدولار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_expenses', to='learning.course', verbose_name='الدورة المرتبطة')),
            ],
            options={
                'verbose_name': 'مصروف تشغيلي',
                'verbose_name_plural': 'المصاريف التشغيلية',
                'ordering': ['-created_at'],
            },
        ),
    ]
