# Generated by Django 6.0.4 on 2026-06-18 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_platformexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformexpense',
            name='expense_type',
            field=models.CharField(choices=[('general', 'عام'), ('printing', 'طباعة')], default='general', max_length=20, verbose_name='نوع المصروف'),
        ),
        migrations.AddField(
            model_name='platformexpense',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار / لم يدفع'), ('paid', 'تم الصرف / مخرّج')], default='paid', max_length=20, verbose_name='حالة المصروف'),
        ),
        migrations.AlterField(
            model_name='platformexpense',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التسجيل'),
        ),
    ]
