# Generated by Django 6.0.4 on 2026-08-30 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_platformexpense_expense_type_platformexpense_status_and_more'),
        ('learning', '0014_course_custom_expense_syp_course_hosting_months_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShamCashInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=80, unique=True, verbose_name='رقم الفاتورة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المطلوب')),
                ('currency', models.CharField(default='SYP', max_length=10, verbose_name='العملة')),
                ('wallet_address', models.CharField(blank=True, max_length=120, verbose_name='محفظة الاستلام')),
                ('status', models.CharField(choices=[('pending', 'معلقة'), ('paid', 'مدفوعة'), ('expired', 'منتهية الصلاحية'), ('failed', 'فشلت')], default='pending', max_length=20, verbose_name='حالة الفاتورة')),
                ('transaction_ref', models.CharField(blank=True, max_length=100, verbose_name='رقم العملية في شام كاش')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='المبلغ المدفوع فعلياً')),
                ('counterparty', models.CharField(blank=True, max_length=120, verbose_name='المُرسِل')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shamcash_invoices', to='learning.course', verbose_name='الدورة')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shamcash_invoices', to='billing.coursepackage', verbose_name='الباقة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shamcash_invoices', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'فاتورة شام كاش',
                'verbose_name_plural': 'فواتير شام كاش',
                'ordering': ['-created_at'],
            },
        ),
    ]
