# Generated by Django 6.0.4 on 2026-05-10 09:33

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringRevenueMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('metric_date', models.DateField(db_index=True, unique=True)),
                ('mrr_cents', models.BigIntegerField(default=0)),
                ('arr_cents', models.BigIntegerField(default=0)),
                ('new_mrr_cents', models.BigIntegerField(default=0)),
                ('churned_mrr_cents', models.BigIntegerField(default=0)),
                ('expansion_mrr_cents', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-metric_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('snapshot_date', models.DateField(unique=True)),
                ('total_active_subscriptions', models.IntegerField(default=0)),
                ('new_subscriptions', models.IntegerField(default=0)),
                ('canceled_subscriptions', models.IntegerField(default=0)),
                ('churn_rate_bps', models.IntegerField(default=0, help_text='Basis points (100 bps = 1%)')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
