# Generated by Django 6.0.4 on 2026-05-10 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_type', models.CharField(db_index=True, default='unknown', max_length=20)),
                ('os_family', models.CharField(blank=True, max_length=50, null=True)),
                ('browser_family', models.CharField(blank=True, max_length=50, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'زيارة للواجهة',
                'verbose_name_plural': 'زيارات الواجهة',
                'ordering': ['-visited_at'],
            },
        ),
    ]
