# Generated by Django 6.0.4 on 2026-05-10 10:48

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Standard Accounting Code e.g. 1101', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Arabic/English Name of Account', max_length=100)),
                ('category', models.CharField(choices=[('asset', 'الأصول (Assets)'), ('liability', 'الالتزامات (Liabilities)'), ('equity', 'حقوق الملكية (Equity)'), ('revenue', 'الإيرادات (Revenue)'), ('expense', 'المصروفات (Expense)')], max_length=20)),
                ('is_group', models.BooleanField(default=False, help_text='If True, serves as parent category folder only and cannot hold transactions directly.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting_erp.account')),
            ],
            options={
                'verbose_name': 'حساب محاسبي',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posting_date', models.DateField(help_text='Date this transaction was incurred (Accrual basis)')),
                ('reference', models.CharField(blank=True, help_text='Invoice #, Payment Ref, etc.', max_length=100)),
                ('memo', models.TextField(blank=True, help_text='General narrative description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('line_memo', models.CharField(blank=True, max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_lines', to='accounting_erp.account')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting_erp.costcenter')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting_erp.journalentry')),
            ],
        ),
    ]
