# Generated by Django 6.0.4 on 2026-05-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code'], 'verbose_name': 'حساب محاسبي', 'verbose_name_plural': 'دليل الحسابات'},
        ),
        migrations.AddField(
            model_name='account',
            name='course_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الدورة'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_course_account',
            field=models.BooleanField(default=False, verbose_name='حساب دورة'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_student_account',
            field=models.BooleanField(default=False, verbose_name='حساب طالب'),
        ),
        migrations.AddField(
            model_name='account',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الحساب (AR)'),
        ),
        migrations.AddField(
            model_name='account',
            name='student_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الطالب'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='cost_center_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='النوع'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('ASSET', 'الأصول (Assets)'), ('LIABILITY', 'الالتزامات (Liabilities)'), ('EQUITY', 'حقوق الملكية (Equity)'), ('REVENUE', 'الإيرادات (Revenue)'), ('EXPENSE', 'المصروفات (Expenses)')], max_length=20, verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='كود الحساب'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_group',
            field=models.BooleanField(default=False, help_text='إذا كان صحيحاً، يعمل كمجلد للفئات ولا يقبل قيوداً مباشرة.'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم الحساب (EN)'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم مركز التكلفة'),
        ),
    ]
