# Generated by Django 6.0.4 on 2026-05-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_erp', '0002_alter_account_options_account_course_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code'], 'verbose_name': 'حساب', 'verbose_name_plural': 'دليل الحسابات'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-posting_date', '-created_at'], 'verbose_name': 'قيد يومية', 'verbose_name_plural': 'قيود اليومية'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='category',
        ),
        migrations.RemoveField(
            model_name='account',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='student_name',
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'أصول (Assets)'), ('LIABILITY', 'خصوم (Liabilities)'), ('EQUITY', 'حقوق ملكية (Equity)'), ('REVENUE', 'إيرادات (Revenue)'), ('EXPENSE', 'مصروفات (Expense)')], default='ASSET', max_length=20, verbose_name='نوع الحساب'),
        ),
        migrations.AddField(
            model_name='account',
            name='course_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='الاسم (AR)'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('MANUAL', 'يدوي (Manual)'), ('RECEIPT', 'سند قبض (Receipt)'), ('PAYMENT', 'سند صرف (Payment)'), ('SALES', 'فاتورة مبيعات (Sales)'), ('ACCRUAL', 'قيد استحقاق (Accrual)'), ('ADJUSTMENT', 'قيد تسوية (Adjustment)')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_posted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_course_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_group',
            field=models.BooleanField(default=False, verbose_name='حساب رئيسي (مجلد)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_student_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الاسم (EN)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='الاسم (AR)'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='cost_center_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='memo',
            field=models.TextField(blank=True, verbose_name='البيان / الوصف'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='posting_date',
            field=models.DateField(verbose_name='تاريخ القيد'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference',
            field=models.CharField(max_length=100, unique=True, verbose_name='المرجع / رقم السند'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='line_memo',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
