# Generated by Django 6.0.4 on 2026-05-10 09:37

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentFailureReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reason_slug', models.CharField(db_index=True, max_length=100)),
                ('occurred_on', models.DateField(db_index=True)),
                ('incident_count', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-occurred_on', '-incident_count'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('gateway_name', models.CharField(db_index=True, max_length=50)),
                ('metric_date', models.DateField(db_index=True)),
                ('successful_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('success_volume_cents', models.BigIntegerField(default=0)),
                ('failed_volume_cents', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-metric_date'],
                'unique_together': {('gateway_name', 'metric_date')},
            },
        ),
    ]
