# Generated by Django 6.0.4 on 2026-05-10 09:38

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastProjections',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('horizon_days', models.IntegerField(choices=[(30, '30 Days Projection'), (90, '90 Days Projection (Quarterly)'), (365, '1 Year Projection')], default=30)),
                ('projected_revenue_cents', models.BigIntegerField()),
                ('confidence_interval_min_cents', models.BigIntegerField()),
                ('confidence_interval_max_cents', models.BigIntegerField()),
                ('model_type', models.CharField(default='linear_regression_simple', max_length=50)),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
    ]
