# Generated by Django 6.0.4 on 2026-05-10 09:33

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPIBenchmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('kpi_key', models.CharField(max_length=100, unique=True)),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('warning_threshold', models.DecimalField(decimal_places=4, help_text='Below this is yellow warning zone.', max_digits=20)),
                ('critical_threshold', models.DecimalField(decimal_places=4, help_text='Below this is red critical zone.', max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KPIRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('kpi_key', models.CharField(db_index=True, help_text="Machine key e.g. 'ARPU', 'NET_PROFIT', 'CHURN_RATE'", max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('record_date', models.DateField(db_index=True)),
                ('unit', models.CharField(choices=[('USD', 'United States Dollar'), ('PERCENT', 'Percentage'), ('COUNT', 'Raw Count'), ('RATIO', 'Ratio')], default='USD', max_length=20)),
            ],
            options={
                'ordering': ['-record_date'],
                'unique_together': {('kpi_key', 'record_date')},
            },
        ),
    ]
