# Generated by Django 6.0.4 on 2026-04-28 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('access', 'Access'), ('attendance', 'Attendance'), ('lesson', 'Lesson'), ('system', 'System')], default='system', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('url', models.CharField(blank=True, max_length=255)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إشعار طالب',
                'verbose_name_plural': 'إشعارات الطلاب',
                'ordering': ['-created_at'],
            },
        ),
    ]
