# Generated by Django 6.0.4 on 2026-05-05 22:01

from django.db import migrations, models


def seed_catalog_sections(apps, schema_editor):
    CatalogSection = apps.get_model("dashboard", "CatalogSection")
    defaults = [
        ("مكثفات العلمي", "intensive", "scientific"),
        ("مكثفات الأدبي", "intensive", "literary"),
        ("منهاج العلمي", "curriculum", "scientific"),
        ("منهاج الأدبي", "curriculum", "literary"),
        ("التاسع", "material", "ninth"),
    ]
    for index, (label, kind, track) in enumerate(defaults, start=1):
        CatalogSection.objects.get_or_create(
            kind=kind,
            track=track,
            defaults={"label": label, "sort_order": index * 10, "is_visible": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('kind', models.CharField(max_length=24)),
                ('track', models.CharField(max_length=24)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فلتر كتالوج',
                'verbose_name_plural': 'فلاتر الكتالوج',
                'ordering': ['sort_order', 'label'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'track'), name='unique_catalog_kind_track')],
            },
        ),
        migrations.RunPython(seed_catalog_sections, migrations.RunPython.noop),
    ]
