# Generated by Django 6.0.4 on 2026-05-14 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_whatsapptemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=40, verbose_name='رقم الهاتف')),
                ('code', models.CharField(max_length=10, verbose_name='الرمز')),
                ('purpose', models.CharField(choices=[('register', 'إنشاء حساب'), ('login', 'تسجيل دخول'), ('reset_password', 'استعادة كلمة المرور')], max_length=20, verbose_name='الغرض')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق؟')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التحقق')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل رمز التحقق',
                'verbose_name_plural': 'سجلات رموز التحقق',
                'ordering': ['-created_at'],
            },
        ),
    ]
