# Generated by Django 6.0.4 on 2026-06-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_otpverificationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=40, verbose_name='رقم الهاتف')),
                ('raw_text_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='هاش النص الخام')),
                ('sent_text', models.TextField(verbose_name='النص المرسل')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
            ],
            options={
                'verbose_name': 'سجل إرسال واتساب',
                'verbose_name_plural': 'سجلات إرسال الواتساب',
                'ordering': ['-sent_at'],
            },
        ),
    ]
