# Generated by Django 6.0.4 on 2026-09-15 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_notebook_details_and_shamcash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookorder',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_notebook_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='مندوب التوصيل المكلف'),
        ),
        migrations.AddField(
            model_name='notebookorder',
            name='driver_heading',
            field=models.FloatField(blank=True, null=True, verbose_name='زاوية اتجاه السائق (Heading)'),
        ),
        migrations.AddField(
            model_name='notebookorder',
            name='driver_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط عرض السائق اللحظي'),
        ),
        migrations.AddField(
            model_name='notebookorder',
            name='driver_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط طول السائق اللحظي'),
        ),
        migrations.AddField(
            model_name='notebookorder',
            name='driver_speed',
            field=models.FloatField(blank=True, null=True, verbose_name='سرعة السائق (كم/سا)'),
        ),
        migrations.AddField(
            model_name='notebookorder',
            name='driver_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت آخر تحديث لإحداثيات السائق'),
        ),
    ]
