# Generated by Django 6.0.4 on 2026-04-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_academicbranch_governorate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='streak_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
