# Generated by Django 6.0.4 on 2026-05-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_last_activity_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/avatars/'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('active', 'نشط'), ('suspended', 'موقوف')], default='active', max_length=20),
        ),
    ]
