# Generated by Django 6.0.4 on 2026-05-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_instructorprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='students/avatars/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
