# Generated by Django 6.0.4 on 2026-05-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentprofile_avatar_studentprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى'), ('unknown', 'غير محدد')], default='unknown', max_length=10, verbose_name='الجنس'),
        ),
    ]
