# Generated by Django on 2026-05-17

from django.db import migrations, models


def copy_username_to_phone(apps, schema_editor):
    InstructorProfile = apps.get_model("accounts", "InstructorProfile")
    for profile in InstructorProfile.objects.select_related("user").iterator():
        if not profile.phone and profile.user_id:
            profile.phone = profile.user.username
            profile.save(update_fields=["phone"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_studentprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructorprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=40, verbose_name="رقم الهاتف"),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="national_id",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name="رقم الهوية"),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="force_password_change",
            field=models.BooleanField(
                default=True,
                help_text="إذا كان صحيحاً، سيطلب من المدرس تغيير كلمة المرور عند أول دخول",
                verbose_name="إجبار تغيير كلمة المرور",
            ),
        ),
        migrations.RunPython(copy_username_to_phone, migrations.RunPython.noop),
    ]
