# Generated by Django 6.0.4 on 2026-06-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_instructorprofile_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='max_daily_otp',
            field=models.PositiveIntegerField(default=10, help_text='الحد الأقصى لرموز التحقق اليومية المسموح بإرسالها للطالب', verbose_name='السقف اليومي لطلب الرموز'),
        ),
    ]
