# Generated by Django 6.0.4 on 2026-06-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_studentprofile_max_daily_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='report_card_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='بيانات بطاقة التقرير المحفوظة'),
        ),
    ]
