# Generated by Django 6.0.4 on 2026-09-15 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_instructorprofile_report_card_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='رقم الهاتف')),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'دراجة نارية'), ('car', 'سيارة'), ('bicycle', 'دراجة هوائية / مشياً'), ('van', 'شاحنة خفيفة / فان')], default='motorcycle', max_length=20, verbose_name='وسيلة النقل')),
                ('is_active', models.BooleanField(default=True, verbose_name='حساب نشط')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح لاستلام الطلبات')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض الحالي')),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول الحالي')),
                ('last_location_update', models.DateTimeField(blank=True, null=True, verbose_name='وقت آخر تحديث للموقع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مندوب توصيل',
                'verbose_name_plural': 'مندوبو التوصيل',
            },
        ),
    ]
