# Generated by Django 6.0.4 on 2026-05-10 09:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_system', '0001_initial'),
        ('learning', '0010_course_allow_pdf_download_course_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('gross_amount_cents', models.BigIntegerField(help_text='Total collected amount before split')),
                ('instructor_share_cents', models.BigIntegerField(help_text='Earnings credited to instructor account')),
                ('status', models.CharField(choices=[('pending', 'Pending Payout'), ('locked', 'Clawback Protection Window'), ('paid', 'Paid to Instructor'), ('reversed', 'Reversed due to Refund')], default='pending', max_length=20)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial_system.financialledger')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstructorPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('payout_cents', models.BigIntegerField()),
                ('payout_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processed', 'Completed Successfully'), ('failed', 'Failed Processing')], default='processed', max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='Bank transaction ID or Provider tracking string', max_length=255)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevenueShareAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('commission_bps', models.IntegerField(default=3000, help_text='Basis points payout to instructor (e.g., 3000 = 30%)')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('course', models.ForeignKey(blank=True, help_text='Leave blank for default shared logic.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('instructor', 'course')},
            },
        ),
    ]
