# Generated by Django 6.0.4 on 2026-05-10 09:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('record_date', models.DateField(db_index=True, unique=True)),
                ('opening_balance_cents', models.BigIntegerField(default=0)),
                ('inflows_cents', models.BigIntegerField(default=0)),
                ('outflows_cents', models.BigIntegerField(default=0)),
                ('closing_balance_cents', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='RevenueSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=20)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('gross_revenue_cents', models.BigIntegerField(default=0)),
                ('net_revenue_cents', models.BigIntegerField(default=0)),
                ('refund_total_cents', models.BigIntegerField(default=0)),
                ('transaction_count', models.IntegerField(default=0)),
                ('active_customers_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'unique_together': {('period', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='FinancialLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entry_type', models.CharField(choices=[('revenue', 'Revenue Inbound'), ('refund', 'Refund Outbound'), ('payout', 'Instructor Payout'), ('expense', 'Operational Expense')], db_index=True, max_length=30)),
                ('amount_cents', models.BigIntegerField(help_text='Amount in smallest currency unit (cents/piasters). Positive for inflow, negative for outflow.')),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('external_reference_id', models.CharField(blank=True, db_index=True, help_text='Reference to billing.Payment.id or similar external PK.', max_length=255, null=True)),
                ('external_source', models.CharField(blank=True, help_text='Source app/table name e.g. billing.Payment', max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Ledger Entry',
                'verbose_name_plural': 'Financial Ledger',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entry_type', 'created_at'], name='financial_s_entry_t_9ec2f8_idx'), models.Index(fields=['external_source', 'external_reference_id'], name='financial_s_externa_d4bece_idx')],
            },
        ),
    ]
