# Generated by Django 6.0.4 on 2026-05-10 09:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1, help_text='Lower value takes precedence if parallel sources provide values.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('base_currency', models.CharField(db_index=True, default='USD', max_length=3)),
                ('quote_currency', models.CharField(db_index=True, default='SYP', max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=20)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='currency_engine.exchangeprovider')),
            ],
            options={
                'ordering': ['-valid_from'],
                'get_latest_by': 'valid_from',
                'indexes': [models.Index(fields=['base_currency', 'quote_currency', 'valid_from'], name='currency_en_base_cu_33a6fb_idx')],
            },
        ),
    ]
