# Generated by Django 6.0.4 on 2026-05-10 09:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('category', models.CharField(choices=[('hosting', 'VPS/Server Hosting'), ('cdn', 'Video CDN Network'), ('storage', 'S3 / Object Storage'), ('bandwidth', 'Bandwidth Overhead'), ('license', 'Software / SSL Licensing')], db_index=True, max_length=30)),
                ('vendor_name', models.CharField(help_text='e.g. AWS, DigitalOcean, Bunny.net', max_length=100)),
                ('monthly_cost_usd_cents', models.BigIntegerField()),
                ('billing_cycle_start', models.DateField()),
                ('is_recurring', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-billing_cycle_start'],
            },
        ),
    ]
