# Generated by Django 6.0.4 on 2026-04-29 02:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_lesson_video_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='academic_track',
            field=models.CharField(choices=[('scientific', 'علمي'), ('literary', 'أدبي'), ('ninth', 'تاسع'), ('general', 'عام')], default='scientific', max_length=24),
        ),
        migrations.AddField(
            model_name='course',
            name='kind',
            field=models.CharField(choices=[('intensive', 'مكثفة'), ('curriculum', 'منهاج'), ('semester', 'فصل'), ('foundation', 'تأسيس'), ('material', 'مادة')], default='intensive', max_length=24),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_photo',
            field=models.ImageField(blank=True, upload_to='courses/teachers/'),
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.CharField(choices=[('full', 'كامل'), ('first', 'الفصل الأول'), ('second', 'الفصل الثاني'), ('summer', 'صيفي')], default='full', max_length=24),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['kind', 'academic_track', 'status'], name='learning_co_kind_b8413f_idx'),
        ),
    ]
