# Generated by Django 6.0.4 on 2026-04-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_course_academic_track_course_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_end_date',
            field=models.DateTimeField(blank=True, help_text='تاريخ انتهاء العرض (إن وجد)', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='course',
            name='students_enrolled',
            field=models.PositiveIntegerField(default=0, help_text='لغرض الدليل الاجتماعي (Social Proof)'),
        ),
    ]
