# Generated by Django 6.0.4 on 2026-05-03 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'شهادة', 'verbose_name_plural': 'الشهادات'},
        ),
    ]
