# Generated by Django 6.0.4 on 2026-05-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_alter_certificate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='kind',
            field=models.CharField(choices=[('intensive', 'مكثفة'), ('curriculum', 'منهاج'), ('semester', 'فصل'), ('foundation', 'تأسيس'), ('material', 'مادة'), ('exam_camp', 'معسكر امتحاني')], default='intensive', max_length=24),
        ),
    ]
