# Generated by Django 6.0.4 on 2026-05-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_alter_course_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='academic_track',
            field=models.CharField(choices=[('scientific', 'علمي'), ('literary', 'أدبي'), ('ninth', 'تاسع'), ('general', 'مشترك')], default='scientific', max_length=24),
        ),
    ]
