# Generated by Django 6.0.4 on 2026-05-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_alter_course_academic_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allow_pdf_download',
            field=models.BooleanField(default=False, help_text='هل يسمح للطالب بتنزيل ملف الـ PDF؟'),
        ),
        migrations.AddField(
            model_name='course',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='ملف الـ PDF الخاص بالدورة كاملة', null=True, upload_to='courses/pdfs/'),
        ),
    ]
