# Generated by Django 6.0.4 on 2026-06-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_course_allow_pdf_download_course_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='units/files/', verbose_name='الملف الشامل الأول'),
        ),
        migrations.AddField(
            model_name='unit',
            name='file1_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='اسم الملف الأول'),
        ),
        migrations.AddField(
            model_name='unit',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='units/files/', verbose_name='الملف الشامل الثاني'),
        ),
        migrations.AddField(
            model_name='unit',
            name='file2_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='اسم الملف الثاني'),
        ),
    ]
