# Generated by Django 6.0.4 on 2026-06-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_unit_file1_unit_file1_name_unit_file2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='file1_name',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='file2_name',
        ),
        migrations.AddField(
            model_name='course',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='courses/files/', verbose_name='الملف الإضافي الأول'),
        ),
        migrations.AddField(
            model_name='course',
            name='file1_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='اسم الملف الأول (على الزر)'),
        ),
        migrations.AddField(
            model_name='course',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='courses/files/', verbose_name='الملف الإضافي الثاني'),
        ),
        migrations.AddField(
            model_name='course',
            name='file2_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='اسم الملف الثاني (على الزر)'),
        ),
    ]
