# Generated by Django 6.0.4 on 2026-06-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_remove_unit_file1_remove_unit_file1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pdf_protected_enabled',
            field=models.BooleanField(default=False, help_text='Enable PDF protection with 2‑use limit'),
        ),
    ]
