# Generated by Django 6.0.4 on 2026-06-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_course_pdf_protected_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='custom_expense_syp',
            field=models.PositiveIntegerField(default=0, verbose_name='مصاريف تشغيل إضافية (ل.س)'),
        ),
        migrations.AddField(
            model_name='course',
            name='hosting_months',
            field=models.PositiveIntegerField(default=1, verbose_name='أشهر الاستضافة'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_account_closed',
            field=models.BooleanField(default=False, verbose_name='حساب الدورة مغلق'),
        ),
        migrations.AddField(
            model_name='course',
            name='settled_instructor_share_syp',
            field=models.PositiveIntegerField(default=0, verbose_name='المبالغ المناقلة للمدرس (ل.س)'),
        ),
    ]
