# Generated by Django 6.0.4 on 2026-05-10 09:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('report_type', models.CharField(choices=[('financial_summary', 'Financial Comprehensive Summary'), ('instructor_payouts', 'Instructor Payout Matrix'), ('subscription_churn', 'Subscription Retention Audit')], max_length=50)),
                ('output_format', models.CharField(choices=[('xlsx', 'Excel Spreadsheet'), ('pdf', 'PDF Document'), ('csv', 'Comma Separated Values')], default='xlsx', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Queued'), ('processing', 'In Progress'), ('completed', 'Completed Success'), ('failed', 'Generation Failure')], default='pending', max_length=20)),
                ('file_asset', models.FileField(blank=True, null=True, upload_to='financial_reports/%Y/%m/')),
                ('filters_json', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
