# Generated by Django 6.0.4 on 2026-05-10 09:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBurnRateReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('period_month', models.DateField(db_index=True, help_text='Use first of month.', unique=True)),
                ('total_infra_burn_usd', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_operational_burn_usd', models.DecimalField(decimal_places=2, max_digits=16)),
                ('composite_burn_total_usd', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
            options={
                'ordering': ['-period_month'],
            },
        ),
        migrations.CreateModel(
            name='OperationalExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('expense_type', models.CharField(choices=[('staff', 'Salaries & Contractors'), ('marketing', 'Advertisements & Branding'), ('office', 'Facilities & Hardware'), ('ai', 'LLM API Costs / Intelligence'), ('other', 'General Operational')], db_index=True, max_length=30)),
                ('label', models.CharField(max_length=150)),
                ('amount_cents', models.BigIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('transaction_date', models.DateField()),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
